### ISSUE TITLE
hip-clang ignores `-fPIE` when compiling for relocatable executables

### ISSUE THREAD

**Issue by robertmaynard** [ROCm/HIP#2168] opened 2020-09-16 19:37 UTC
When compiling for whole compilation with `-fPIE` hip-clang will produce the following error:

```
 error: relocation R_AMDGPU_REL32_HI cannot be used against symbol
```

Is there a limitation on why the relocatable nature of `-fPIE` isn't sufficient for `hip`? If so we should either:

- error when `-fPIE` is provided instead of silently dropping it
- convert it to `-fPIC` as the user requested a form of relocation

**Comment by dmcdougall** [comment] 2020-09-21 17:26
Do you have a simple reproducer?

**Comment by robertmaynard** [comment] 2020-09-21 18:08
It looks like this is tied to optimization levels.

Works:
```
hipcc -fPIE -std=c++14 -c shared.hip -o shared.o -O3
hipcc -fPIE -std=c++14 -c shared.hip -o shared.o -O2
hipcc -fPIE -std=c++14 -c shared.hip -o shared.o -O1
```

Fails:
```
hipcc -fPIE -std=c++14 -c shared.hip -o shared.o -O0

/opt/rocm/llvm/bin/clang++ -D__HIP_ROCclr__=1 -fPIE --hip-device-lib-path=/opt/rocm/lib -mllvm \
   -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false \
   -l/opt/rocm-3.7.0/llvm/lib/clang/11.0.0/lib/linux/libclang_rt.builtins-x86_64.a \
   -pthread -std=c++14 -o shared.cxx.o -x hip -c shared.hip \
   -I/opt/rocm-3.7.0/hip/include \
   -isystem /opt/rocm-3.7.0/hip/include \
   -I /opt/rocm-3.7.0/llvm/lib/clang/11.0.0 \
   -isystem /opt/rocm-3.7.0/llvm/lib/clang/11.0.0 \
```

Simple Reproducer Code:
```cpp
#include <hip/hip_runtime.h>

#define VTKM_EXEC __host__ __device__
#define VTKM_EXEC_CONT __host__ __device__
#define VTKM_CONT __host__


#define VTKM_ALWAYS_EXPORT [[gnu::visibility("default")]]

/// \brief An implicit array portal that returns an counting value.
template <class CountingValueType>
class VTKM_ALWAYS_EXPORT ArrayPortalCounting
{
  using ComponentType = float;

public:
  using ValueType = CountingValueType;

  VTKM_EXEC_CONT
  ArrayPortalCounting()
    : Start(0)
    , Step(1)
    , NumberOfValues(0)
  {
  }

  VTKM_EXEC_CONT
  ArrayPortalCounting(ValueType start, ValueType step, int numValues)
    : Start(start)
    , Step(step)
    , NumberOfValues(numValues)
  {
  }

  template <typename OtherValueType>
  VTKM_EXEC_CONT ArrayPortalCounting(const ArrayPortalCounting<OtherValueType>& src)
    : Start(src.Start)
    , Step(src.Step)
    , NumberOfValues(src.NumberOfValues)
  {
  }

  template <typename OtherValueType>
  VTKM_EXEC_CONT ArrayPortalCounting<ValueType>& operator=(
    const ArrayPortalCounting<OtherValueType>& src)
  {
    this->Start = src.Start;
    this->Step = src.Step;
    this->NumberOfValues = src.NumberOfValues;
    return *this;
  }

  VTKM_EXEC_CONT
  ValueType GetStart() const { return this->Start; }

  VTKM_EXEC_CONT
  ValueType GetStep() const { return this->Step; }

  VTKM_EXEC_CONT
  int GetNumberOfValues() const { return this->NumberOfValues; }

  VTKM_EXEC_CONT
  ValueType Get(int index) const
  {
    return ValueType(this->Start + this->Step * ValueType(static_cast<ComponentType>(index)));
  }

private:
  ValueType Start;
  ValueType Step;
  int NumberOfValues;
};

template<typename T>
class VTKM_ALWAYS_EXPORT ArrayPortalWrite
{
public:
  using ValueType = T;
  VTKM_EXEC_CONT
  ArrayPortalWrite()
    : Start(nullptr)
    , NumberOfValues(0)
  {
  }

  VTKM_EXEC_CONT
  ArrayPortalWrite(ValueType* start, int numValues)
    : Start(start)
    , NumberOfValues(numValues)
  {
  }

  VTKM_EXEC_CONT
  int GetNumberOfValues() const { return this->NumberOfValues; }

  VTKM_EXEC_CONT
  void Set(int index, ValueType const& v) const
  {
    this->Start[index]=v;
  }

private:
  ValueType* Start;
  int NumberOfValues;
};


template <class InputPortalType, class OutputPortalType>
struct CopyKernel
{
  InputPortalType InputPortal;
  OutputPortalType OutputPortal;
  int InputOffset;
  int OutputOffset;

  VTKM_CONT
  CopyKernel(InputPortalType inputPortal,
             OutputPortalType outputPortal,
             int inputOffset = 0,
             int outputOffset = 0)
    : InputPortal(inputPortal)
    , OutputPortal(outputPortal)
    , InputOffset(inputOffset)
    , OutputOffset(outputOffset)
  {
  }

  VTKM_EXEC
  void operator()(int index) const
  {
    using ValueType = typename OutputPortalType::ValueType;
    this->OutputPortal.Set(
      index + this->OutputOffset,
      static_cast<ValueType>(this->InputPortal.Get(index + this->InputOffset)));
  }
};


template<typename KernelEngine>
__global__ void exec_kernel(KernelEngine ke, int size) {

  for(int i=0; i < size; ++i)
  {
    ke(i);
  }
}

__host__ bool launch_kernel()
{
  float* ptr = nullptr;

  ArrayPortalCounting<int> a(0,1,10);
  ArrayPortalWrite<float> b(ptr,10);
  CopyKernel<decltype(a), decltype(b)> ck(a,b);

  exec_kernel<<<1,1>>>(ck, 10);

  return 0;
}

```

**Comment by yxsamliu** [comment] 2020-09-21 20:02
This is because clang driver passed -fPIE to device compilation whereas amdgpu backend does not support that. We will fix it by filtering out -fPIE for device compilation.

**Comment by dmcdougall** [comment] 2020-09-21 20:04
Thank you Sam.

**Comment by yxsamliu** [comment] 2024-03-20 04:34
fixed by https://github.com/llvm/llvm-project/commit/10eb3bf2d430825195bf092d3a75c4745d463826

**Closed by yxsamliu** 2024-03-20 04:34 UTC
