### ISSUE TITLE
Failed run tensorflow 2.3.0 with rocm 3.9.0(/src/external/hip-on-vdi/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!"))

### ISSUE THREAD

**Issue by zoran-liu** [ROCm/HIP#2187] opened 2020-11-05 16:09 UTC
/src/external/hip-on-vdi/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")

**Comment by xuhuisheng** [comment] 2020-11-05 21:19
Duplicate of https://github.com/RadeonOpenCompute/ROCm/issues/1269

**Comment by cjatin** [comment] 2020-11-10 12:17
Which GPU are you running it on?

**Comment by zoran-liu** [comment] 2020-11-10 16:34
> Which GPU are you running it on?

RX 5700

**Comment by zoran-liu** [comment] 2020-11-10 16:35
> Duplicate of [RadeonOpenCompute/ROCm#1269](https://github.com/RadeonOpenCompute/ROCm/issues/1269)

I test rocspare with source code and get same error

**Comment by zoran-liu** [comment] 2020-11-10 16:36
Agent 2                  
*******                  
  Name:                    gfx1010                            
  Uuid:                    GPU-XX                             
  Marketing Name:          Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)

**Comment by zoran-liu** [comment] 2020-11-10 16:37
Ubuntu 20.04.1 LTS

**Comment by xuhuisheng** [comment] 2020-11-11 00:03
@zoran-liu RX 5700 please refer this issue : https://github.com/ROCmSoftwarePlatform/pytorch/issues/718#issuecomment-720172421

**Comment by 2017040264** [comment] 2020-12-17 09:55
I have the same error in ubuntu18.04.5 + Radeon Rx Vega10 Graphics.

**Comment by ppanchad-amd** [comment] 2024-03-20 01:37
Fixed in latest ROCm 6.0.2 (HIP 6.0.32831). Closing Ticket

**Closed by ppanchad-amd** 2024-03-20 01:37 UTC
