### ISSUE TITLE
hipcc linker error: hipcc VS nvcc 

### ISSUE THREAD

**Issue by HWang-Summit** [ROCm/HIP#2196] opened 2020-12-02 11:39 UTC
**I am porting a CUDA project to HIP. I converted my code through "hipconvertinplace-perl.sh" (I am sure this step is correct), and encountered some problems when compiling and linking, as shown below:**
**1. First of all, this is the makefile of my original cuda project：**
```
CUDA_PATH   ?=/usr/local/cuda-10.2
NVCC        :=$(CUDA_PATH)/bin/nvcc
INCLUDE     :=-I/home/summit/.local/cfitsio/include\
			-I/home/summit/.local/wcslib/include/wcslib\
			-I./
LIBRARIES   :=-L/home/summit/.local/cfitsio/lib\
              -L/home/summit/.local/wcslib/lib	      
CUDA_ARCH=-gencode arch=compute_35,code=sm_35 \
		  -gencode arch=compute_50,code=sm_50 \
		  -gencode arch=compute_60,code=sm_60\

NVCC_FLAGS := -Wno-deprecated-gpu-targets -dc
CXX_FLAGS := -std=c++11
FITS_FLAGS := -lm -lcfitsio -lwcs

helpers.o: helpers.cu
	$(NVCC) -O3 -ccbin $(CXX) $(NVCC_FLAGS) -o $@ -c $<

healpix.o: healpix.cu
	$(NVCC) -O3 -ccbin $(CXX) $(NVCC_FLAGS) -o $@ -c $<

gmap.o: gmap.cpp
	$(NVCC) -O3 -ccbin $(CXX) $(NVCC_FLAGS) $(INCLUDE) -o $@ -c $<

gridding.o: oleder.cu
	$(NVCC) -O3 -ccbin $(CXX) $(NVCC_FLAGS) $(INCLUDE) -o $@ -c $<

main.o: main.cpp
	$(NVCC) -O3 -ccbin $(CXX) $(NVCC_FLAGS) -o $@ -c $<

HCGrid: helpers.o healpix.o gmap.o gridding.o main.o
	@ echo ./$@ $+
	$(NVCC) -O3 -ccbin $(CXX) -Wno-deprecated-gpu-targets -o $@ $+ $(CUDA_ARCH) $(LIBRARIES) $(FITS_FLAGS)
```
**2. Then I have rewritten the makefile for hipcc compilation, as follows:**
```
HIP_PATH    ?=/opt/rocm-3.9.0
HIPCC       :=$(HIP_PATH)/bin/hipcc
INCLUDE     :=-I/home/summit/.local/cfitsio/include\
			  -I/home/summit/.local/wcslib/include/wcslib\
			  -I./
LIBRARIES   :=-L/home/summit/.local/cfitsio/lib\
              -L/home/summit/.local/wcslib/lib
HIPCC_FLAGS := -Wno-deprecated-register -dc
CXX_FLAGS := -std=c++11
FITS_FLAGS := -lm -lcfitsio -lwcs

helpers.o: helpers.cu
	$(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ -c $<

healpix.o: healpix.cu
	$(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ -c $<

gmap.o: gmap.cpp
	$(HIPCC) -O3 $(HIPCC_FLAGS) $(CXX_FLAGS) $(INCLUDE) -o $@ -c $<

gridding.o: oleder.cu
	$(HIPCC) -O3 $(HIPCC_FLAGS) $(CXX_FLAGS) $(INCLUDE) -o $@ -c $<

main.o: main.cpp
	$(HIPCC) -O3 $(HIPCC_FLAGS) $(CXX_FLAGS) -o $@ -c $<

HCGrid: helpers.o healpix.o gmap.o gridding.o main.o
	@ echo ./$@ $+
	$(HIPCC) -O3 -o $@ $+ $(LIBRARIES) $(FITS_FLAGS) $(CXX_FLAGS)
```
**3. When I was compiling, the following error occurred. Can you tell me what caused this? Are there any suggestions to help me solve it? Is the makfile I rewritten wrong? To be honest, I am not very clear about the similarities and differences between the compilation options of hipcc and nvcc**

lld: error: undefined hidden symbol: d_ang2pix(double, double)
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))

lld: error: undefined hidden symbol: d_pix2ring(unsigned long)
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))

lld: error: undefined protected symbol: d_const_Healpix
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))
>>> referenced 1 more times

lld: error: undefined hidden symbol: d_get_ring_info_small(unsigned long, unsigned long&, unsigned long&, bool&)
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))

lld: error: undefined hidden symbol: d_pix2ang(unsigned long, double&, double&)
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))

lld: error: undefined hidden symbol: true_angular_distance(double, double, double, double)
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))

lld: error: undefined hidden symbol: great_circle_bearing(double, double, double, double)
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))
>>> referenced by /tmp/oleder-gfx906-9b9e18.o:(hcgrid(double*, double*, double*, double*, double*, double*, double*, double*, unsigned int*, unsigned long*))
clang-12: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)

**Comment by HWang-Summit** [comment] 2020-12-03 01:34
I think this is more than a question. I rewrote the Makefile through the manual provided by HIP. I saw other people have mentioned similar problems, but it seems to be of no help.

**Comment by zjin-lcf** [comment] 2020-12-07 20:35
May you compile the converted HIP files using just hipcc  ?

I encountered the hidden symbol errors too. Could you check if it works using '-fgpu-rdc' when compiling your source files ?

**Comment by HWang-Summit** [comment] 2020-12-08 02:24
Did you mean "HIPCC_FLAGS :=  -fgpu-rdc  -Wno-deprecated-register -dc" ?

zjin-lcf <notifications@github.com> 于2020年12月8日周二 上午4:35写道：

**Comment by zjin-lcf** [comment] 2020-12-08 04:51
The issue #2203 was closed

**Comment by HWang-Summit** [comment] 2020-12-08 07:42
I set the "HIPCC_FLAGS" as  HIPCC_FLAGS := -fgpu-rdc --hip-link  -Wno-deprecated-register, it's also produces the message "undefined reference to `__hip_fatbin'", could you solve it?

**Comment by HWang-Summit** [comment] 2020-12-08 07:43
> The issue #2203 was closed
I set the "HIPCC_FLAGS" as HIPCC_FLAGS := -fgpu-rdc --hip-link -Wno-deprecated-register, it's also produces the message "undefined reference to `__hip_fatbin'", could you solve it?

**Comment by yxsamliu** [comment] 2020-12-08 15:51
your make file does not use HIPCC_FLAGS in link command. You may need HIPCC_LINK_FLAGS and add --hip-link -fgpu-rdc there.

**Comment by HWang-Summit** [comment] 2020-12-09 02:23
> your make file does not use HIPCC_FLAGS in link command. You may need HIPCC_LINK_FLAGS and add --hip-link -fgpu-rdc there.

Thank you very much!  I set  the link command, and update the makefile as follows, however, it produces the following message, while the Cuda version does not have this error.
```
HIP_PATH    ?=/opt/rocm-3.9.0
HIPCC       :=$(HIP_PATH)/bin/hipcc
INCLUDE     :=-I/home/summit/.local/cfitsio/include\
                          -I/home/summit/.local/wcslib/include/wcslib\
                          -I./
LIBRARIES   :=-L/home/summit/.local/cfitsio/lib\
              -L/home/summit/.local/wcslib/lib

HIPCC_FLAGS := -fgpu-rdc --hip-link -Wno-deprecated-register
#HIPCC_LINK_FLAGS := --hip-link -fgpu-rdc
CXX_FLAGS := -std=c++11
FITS_FLAGS := -lm -lcfitsio -lwcs

helpers.o: helpers.cu
        $(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ -c $<

healpix.o: healpix.cu
        $(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ -c $<

gmap.o: gmap.cpp
        $(HIPCC) -O3 $(HIPCC_FLAGS) $(INCLUDE) -o $@ -c $<

gridding.o: oleder.cu
        $(HIPCC) -O3 $(HIPCC_FLAGS) $(INCLUDE) -o $@ -c $<

main.o: main.cpp
        $(HIPCC) -O3 $(HIPCC_FLAGS)  -o $@ -c $<

HCGrid: helpers.o healpix.o gmap.o gridding.o main.o
        @ echo ./$@ $+
        $(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ $+ $(LIBRARIES) $(FITS_FLAGS)

clean:
        rm -rf *.o HCGrid
```

```
oleder.cu:(.text+0x11d9): undefined reference to `d_const_Healpix'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by zjin-lcf** [comment] 2020-12-09 02:39
Could you please provide a repository for reproducing errors if your application is open source ?

**Comment by HWang-Summit** [comment] 2020-12-09 03:04
> Could you please provide a repository for reproducing errors if your application is open source ?
Sure, I  create a New repository "https://github.com/HWang-Summit/HCGrid-AMD", looking forward to getting your help again!

**Comment by zjin-lcf** [comment] 2020-12-09 15:10
Could you suggest the specific command line options for HCGrid to verify the results on an Nvidia or AMD GPU ?  

```
useage: ./HCGrid --fits_path <absolute path> --input_file <input file> --target_file <target file> --sorted_file <sorted file> --output_file <output file> --fits_id <number> --beam_size <beam> --order_arg <order> --block_num <num>  --coarsening_factor<factor>
```

**Comment by HWang-Summit** [comment] 2020-12-09 15:46
I'm sorry, I'm not sure what you mean. Do you mean how to verify the correctness of result after "make"?  If so, it would be correct if you execute "./HCGrid -h" and get the "usage information" as you wrote. And  the specific command line approach requires the use of test data. Thank you for your help and look forward to receiving any suggestions from you!
2020年12月9日 +0800 23:11 zjin-lcf <notifications@github.com>，写道：

**Comment by HWang-Summit** [comment] 2020-12-10 02:03
> Could you suggest the specific command line options for HCGrid to verify the results on an Nvidia or AMD GPU ?
> 
> ```
> useage: ./HCGrid --fits_path <absolute path> --input_file <input file> --target_file <target file> --sorted_file <sorted file> --output_file <output file> --fits_id <number> --beam_size <beam> --order_arg <order> --block_num <num>  --coarsening_factor<factor>
> ```


I'm sorry, I'm not sure what you mean. Do you mean how to verify the correctness of result after "make"?  If so, it would be correct if you execute "./HCGrid -h" and get the "usage information" as you wrote. And  the specific command line approach requires the use of test data. Thank you for your help and look forward to receiving any suggestions from you!

**Comment by zjin-lcf** [comment] 2020-12-10 13:00
This is what I did:

move ```__constant__ Healpix d_const_Healpix;``` to the file where other constant memories are defined.

In Makefile, you may change
```
helpers.o: helpers.cu
	$(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ -c $<

healpix.o: healpix.cu
	$(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ -c $<

gmap.o: gmap.cpp
	$(HIPCC) -O3 $(HIPCC_FLAGS) $(INCLUDE) -o $@ -c $<

gridding.o: oleder.cu
	$(HIPCC) -O3 $(HIPCC_FLAGS) $(INCLUDE) -o $@ -c $<

main.o: main.cpp
	$(HIPCC) -O3 $(HIPCC_FLAGS)  -o $@ -c $<

HCGrid: helpers.o healpix.o gmap.o gridding.o main.o
	@ echo ./$@ $+
	$(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ $+ $(LIBRARIES) $(FITS_FLAGS)
``` 

to

```
HIPCC_FLAGS := -fgpu-rdc -Wno-deprecated-register
HIPCC_LINK_FLAGS := -fgpu-rdc --hip-link
CXX_FLAGS := -std=c++11
FITS_FLAGS := -lm -lcfitsio -lwcs

HCGrid: helpers.o healpix.o gmap.o gridding.o main.o
        #@ echo ./$@ $+
        $(HIPCC) -O3 -o $@ $+ $(LIBRARIES) $(FITS_FLAGS) $(HIPCC_LINK_FLAGS)

helpers.o: helpers.cu
        $(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ -c $<

healpix.o: healpix.cu
        $(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ -c $<

gmap.o: gmap.cu
        $(HIPCC) -O3 $(HIPCC_FLAGS) $(INCLUDE) -o $@ -c $<

gridding.o: oleder.cu
        $(HIPCC) -O3 $(HIPCC_FLAGS) $(INCLUDE) -o $@ -c $<

main.o: main.cu
        $(HIPCC) -O3 $(HIPCC_FLAGS)  -o $@ -c $<

```

" the specific command line approach requires the use of test data." May you update your HCGrid documentation with some specific command line values for performance evaluation of your application ?

**Comment by HWang-Summit** [comment] 2020-12-11 03:19
> This is what I did:
> 
> move `__constant__ Healpix d_const_Healpix;` to the file where other constant memories are defined.
> 
> In Makefile, you may change
> 
> ```
> helpers.o: helpers.cu
> 	$(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ -c $<
> 
> healpix.o: healpix.cu
> 	$(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ -c $<
> 
> gmap.o: gmap.cpp
> 	$(HIPCC) -O3 $(HIPCC_FLAGS) $(INCLUDE) -o $@ -c $<
> 
> gridding.o: oleder.cu
> 	$(HIPCC) -O3 $(HIPCC_FLAGS) $(INCLUDE) -o $@ -c $<
> 
> main.o: main.cpp
> 	$(HIPCC) -O3 $(HIPCC_FLAGS)  -o $@ -c $<
> 
> HCGrid: helpers.o healpix.o gmap.o gridding.o main.o
> 	@ echo ./$@ $+
> 	$(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ $+ $(LIBRARIES) $(FITS_FLAGS)
> ```
> 
> to
> 
> ```
> HIPCC_FLAGS := -fgpu-rdc -Wno-deprecated-register
> HIPCC_LINK_FLAGS := -fgpu-rdc --hip-link
> CXX_FLAGS := -std=c++11
> FITS_FLAGS := -lm -lcfitsio -lwcs
> 
> HCGrid: helpers.o healpix.o gmap.o gridding.o main.o
>         #@ echo ./$@ $+
>         $(HIPCC) -O3 -o $@ $+ $(LIBRARIES) $(FITS_FLAGS) $(HIPCC_LINK_FLAGS)
> 
> helpers.o: helpers.cu
>         $(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ -c $<
> 
> healpix.o: healpix.cu
>         $(HIPCC) -O3 $(HIPCC_FLAGS) -o $@ -c $<
> 
> gmap.o: gmap.cu
>         $(HIPCC) -O3 $(HIPCC_FLAGS) $(INCLUDE) -o $@ -c $<
> 
> gridding.o: oleder.cu
>         $(HIPCC) -O3 $(HIPCC_FLAGS) $(INCLUDE) -o $@ -c $<
> 
> main.o: main.cu
>         $(HIPCC) -O3 $(HIPCC_FLAGS)  -o $@ -c $<
> ```
> 
> " the specific command line approach requires the use of test data." May you update your HCGrid documentation with some specific command line values for performance evaluation of your application ?


“ move `__constant__ Healpix d_const_Healpix;` to the file where other constant memories are defined”，
**at present, the __constant__ Healpix d_const_Healpix are defined in healpix.cu,  The method you provide is to move it to other constant memory definition files, but d_const_Healpix should also be called in the healpix.cu file. So, moving to another file is wrong, right?**

**Comment by zjin-lcf** [comment] 2020-12-11 03:41
Could you confirm if you still see the error after updating your repository with the changes ?

If the compile is successful, please report the issue to https://github.com/yxsamliu

**Comment by HWang-Summit** [comment] 2020-12-11 05:47
> Could you confirm if you still see the error after updating your repository with the changes ?
> 
> If the compile is successful, please report the issue to https://github.com/yxsamliu


Thank you! The compilation is successful! I am testing the performance, and then I will update the test data to the repository.  And how to report issue to https://github.com/yxsamliu?

**Comment by zjin-lcf** [comment] 2020-12-11 10:24
"The method you provide is to move it to other constant memory definition files, but d_const_Healpix should also be called in the healpix.cu file. So, moving to another file is wrong, right?"  Since the compilation is successful and you don't need to make such change using nvcc, please direct your question to AMD. Sorry, I am not clear about the cause. 

I made a comment here about the CUDA version: https://github.com/HWang-Summit/HCGrid/issues/1#issue-761756172, so memory accesses may be out of bound for the HIP version too. 

You are welcome.

**Comment by ppanchad-amd** [comment] 2024-03-20 01:47
@HWang-Summit, Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.

**Closed** 2024-04-02 13:54 UTC
Labels: type:question
